version: '3'

services:
  app:
    build: .
    container_name: 'micro-videos-typescript-app'
    command: ./start.sh
    links:
      - "db"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: 'micro-videos-typescript-db'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    command: --innodb-use-native-aio=0
